version: "2"

services:
  client:
    build:
      context: ./cybersec_build
      args:
        - USER_ID=$USER_ID
    env_file:
      - .env_secret.env
    command: sh -c 'git clone https://github.com/yeisonlegarda/CybersecBlockChainClient.git;cd CybersecBlockChainClient;npm dedupe;npm install;npm install web3@0.20.6;ng serve --host 0.0.0.0'
    ports:
      - '4200:4200'
      - '35729:35729'
    volumes:
      - ./workspace/angular:/workspace/angular
    user: "$USER_ID"
